### ISSUE TITLE
Calculate failed last check

### ISSUE THREAD

**Issue by DaveY95** [WincAcademy/wincpy#11]
code: https://github.com/Juliazijd/winc_back-end/tree/main/calculate
OS: MacOS
Tried solutions: python -m wincpy update

**Comment by stfwn** [comment]
Just to be sure: is the problem that the linked code does not pass even though it should?

I don't own a Mac so I can't reproduce.

**Comment by DaveY95** [comment]
Yes, the code seems all fine. I copied the code and ran it on my own VScode and it passed. The student however still has a :thumbs down: at the last check _discounted sum total_.

**Comment by stfwn** [comment]
If anyone with a Mac can take a look at this (preferably on the new check system) that'd be great.

**Comment by nielsbom** [comment]
[This student](https://winc-campus.slack.com/archives/C01BP2F5RQS/p1633605882301000) had the same problem. cc @simplect 
Can you add the code here too @simplect ?

**Comment by DaveY95** [comment]
Error is still active, now also for windows 11 Home version. 
Tried to solve it with command: `python -m wincpy upgrade`
But still same error.
