### ISSUE TITLE
wincpy check can't find __winc_id__ prop on specific Windows machine

### ISSUE THREAD

**Issue by nielsbom** [WincAcademy/wincpy#2]
OK, updated the title.
We have a single student (PK) who sees this behaviour:

- `wincpy check` in the dir with a seemingly valid `main.py`
- error: `This module does not have a Winc ID.`
- so somewhere [here](https://github.com/WincAcademy/wincpy/blob/master/wincpy/helpers.py#L116)

@dmvandenberg checked this on his Windows machine, with Powershell also but then it worked.

Very mysterious.
@stfwn could you please contact the student and help troubleshoot?

Thanks!

**Comment by nielsbom** [comment]
Net ook confirmed op Linux, dus denk niet dat het een OS ding is.

**Comment by stfwn** [comment]
Dit is geen bug, `__init__.py` is niet nodig. Wincpy importeert `main.py` als module, dan werken imports voor het importeren en het draaien van `main.py` als entrypoint (`python main.py`). Wat is het onderliggende probleem waardoor je dacht dat dat wel zo was?

Er zijn overigens nog starts en solutions met een `__init__.py`, Wincpy is er compatible mee maar de voorkeur gaat uit naar zonder (zie README).

**Comment by nielsbom** [comment]
OK, updated the title.
We have a single student (PK) who sees this behaviour:

- `wincpy check` in the dir with a seemingly valid `main.py`
- error: `This module does not have a Winc ID.`
- so somewhere [here](https://github.com/WincAcademy/wincpy/blob/master/wincpy/helpers.py#L116)

@dmvandenberg checked this on his Windows machine, with Powershell also but then it worked.

Very mysterious.
@stfwn could you please contact the student and help troubleshoot?

Thanks!

**Comment by nielsbom** [comment]
Did the student's reinstall fix the problem @stfwn ?
If yes, let's close this.

**Comment by stfwn** [comment]
Student reinstalled Python on their machine. This fixed the issue. No issues with WincPy identified, closing.
