### ISSUE TITLE
Wincpy start issue with Bart Winter

### ISSUE THREAD

**Issue by DaveY95** [WincAcademy/wincpy#22]
Last week there was an error posted about the wincpy start command. 
Each time when he calls a wincpy start command it returns FileNotFoundError: [WinError 2].
I tried multiple solutions:
- updating wincpy
- updating pip
- reinstalling python and add PATH again.

Still the same errors. The only solution now that he can make it work is to use the wincpy start at a different path. The only path that now seems to work is at the following:
`C:\User\Bart->`
But if it's beyond that it won't work even not in documents. Here are some screenshots from the errors. 
![image (1)](https://user-images.githubusercontent.com/27994244/146543849-96c44c5e-6b36-493e-a285-cf1fb98c3f4b.png)
![image](https://user-images.githubusercontent.com/27994244/146543853-e9189a71-cc4b-49d0-a06b-7af50f8e6987.png)

**Comment by stfwn** [comment]
Interesting. I'd want to interactively debug with them to gather some more info on how stuff is laid out on their system. Do they still have this problem?
