### ISSUE TITLE
"dictionaries" exercise weirdness

### ISSUE THREAD

**Issue by nielsbom** [WincAcademy/wincpy#23]
A student reported this:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/327080/148419185-87edac40-5298-496e-a3a3-cb3e73d6cbc6.png">

Note the `place_of_birht` dict key and wincpy:
- giving a fail
- saying it's implemented correctly
- giving the "tip" that the code is a correct implementation

**Comment by stfwn** [comment]
- The 'tip' was incorrectly worded and I fixed this just now in main, thanks!
- Giving a fail looks correct to me
- The '.. is implemented correctly' is in the 'requirement' column with the 'pass/fail' column indicating whether this requirement has been met (in this case it hasn't).

Does that close this?

**Comment by nielsbom** [comment]
> The 'tip' was incorrectly worded and I fixed this just now in main, thanks!

Thanks!
Shall we release?

> Giving a fail looks correct to me

Agreed. The combination of things was weird.

> The '.. is implemented correctly' is in the 'requirement' column with the 'pass/fail' column indicating whether this requirement has been met (in this case it hasn't).

Ahhh, I didn't read the table header, derp. Can we rewrite this to be even more obvious? Something like `create_passport needs to be implemented correctly`? The iceberg-perspective tells me I can't be the only one that had some confusion here.

Or maybe it's the column order that I tripped over. Isn't the following column order more logical?

1. requirement (what needs doing)
2. pass/fail (whether that worked)
3. tips

It's visually a little less nice because the icons aren't on the left.

**Comment by Chrisztiaan** [comment]
message changed in 1.1.3
Also asked course dev to change course so it's more clear that the arguments should be name, date_of_birth, place_of_birth, height, nationality.
