### ISSUE TITLE
'while' exercise does not display wincpy check errors in table form

### ISSUE THREAD

**Issue by RishaanvB** [WincAcademy/wincpy#25]
Student reports that the tip-columns for the exercise 'while' does not display the tips in column format:
![image](https://user-images.githubusercontent.com/69298949/149809555-f0adc6e0-1e04-4f6a-8faf-8e2977c4ccf7.png)
But instead does not show anything. 

It does work for other exercises.

**Comment by RishaanvB** [comment]
Steps student has taken:
1. removed while folder and initiated a new instance with `wincpy start xxxx` 
2. restart pc
3. initiated with `python -m wincpy check`
platform: macOS

I've asked if student also tried  `python3 -m wincpy check`, but no answer yet. 
I cannot reproduce this issue, columns/table are working fine for me.

**Comment by stfwn** [comment]
Does your screenshot show the bugged or OK outcome?

If the former, this does look like intended behavior (unless I'm overlooking something in the screenshot) and it's more of a UI/UX problem. We've had confusion about the table before so it would be worth checking how many people are actually confused about this.

If the latter, can you ask for the exit code? (`echo $?` in Bash/Zsh). I'll see if I can find a path through the logic that results in nothing being printed.

**Comment by RishaanvB** [comment]
@stfwn screenshot is from the OK output, not the bugged one. 
This is a screenshot of the code snippet the student provided:
![image](https://user-images.githubusercontent.com/69298949/149912352-37403b0d-a028-4efa-b40e-79cbcf4eba17.png)

I'll ask for the exit code.

**Comment by RishaanvB** [comment]
I'll close this. It's not relevant anymore. The issue was not wincpy, but me not checking the students code properly. Code got stuck in a while loop, so that's why it didn't show any results.
