### ISSUE TITLE
No check "Lists"

### ISSUE THREAD

**Issue by NSombekke** [WincAcademy/wincpy#26]
Wincpy indicates that there is no check for the exercise/assignment lists (https://winc.talentlms.com/unit/view/id:4764)

**Comment by nielsbom** [comment]
Worked for me.
@NSombekke will recheck with the student.

**Comment by RishaanvB** [comment]
I checked with the student and there was probably some initial issue that the student wasn't aware of. 
Resolved by:
Student removed the lists folder and re-initialized wincpy start xxx and everything worked. 

Can be closed.
