### ISSUE TITLE
Wincpy check in files exercise does not check for find_password

### ISSUE THREAD

**Issue by RishaanvB** [WincAcademy/wincpy#28]
The last check for the find_password function in wincpy check isn't properly implemented. 

Problem:
It always returns a pass for the last check as long as the function exists in the main.py file. 

Reproduce:
Use:
`def find_password(cached_files):
    pass`

then do a wincpy check and see that it returns a pass for part 4 of the exercise. 

Possible reason for not returning correct check:

De check currently doesn't do an assert on the 
`student_module.find_password(
        student_module.cached_files()
    ) == "correct_horse_battery_staple", "The returned password is not correct."`

**Comment by stfwn** [comment]
Nice catch, and your fix is exactly correct, thank you! Feel free to write a PR for this type of stuff if you have the time.

**Comment by RishaanvB** [comment]
@stfwn  The credit goes to one of the students who reported the initial issue. 

Am I correct in saying that wincpy needs to be updated to v1.1.1 in order to reflect these changes? ie: Do I need to make a slack-wide comment for all the students to update their wincpy?

> Feel free to write a PR for this type of stuff if you have the time.

Yes, I will.

**Comment by stfwn** [comment]
> The credit goes to one of the students who reported the initial issue.

That's great!

> Do I need to make a slack-wide comment for all the students to update their wincpy?

Sure, it's always good to keep Winc pies up to date :pie:
