### ISSUE TITLE
Wincpy checks needs some extra checks in 'for' exercise alphabet set.

### ISSUE THREAD

**Issue by RishaanvB** [WincAcademy/wincpy#29]
The wincpy check for the alphabet_set function currently only checks if the return value contains all the letters of the alphabet as far as I could tell. 

EDIT: Check can be found here: https://github.com/WincAcademy/wincpy/blob/main/wincpy/checks/c545bc87620d4ced81cbddb8a90b4a51.py

I did some testing:
```
 def alphabet_set(countries):
     return 'abcdefghijklmnopqrstuqvwxyz'
```
returns an OK.

And just simply returning the argument given returns an OK. 
edit: in this exercise 'countries' is a list of x-amount of strings, so simply returning the argument given wouldn't always gives an OK from wincpy, but in the case for this exercise 'countries' is a list of countryname strings which combined have all the letters [a-z]

```
def alphabet_set(countries):
    return countries
```

Currently the checks look like this:

```
def check_alphabet_set(student_module):
    StandardChecks.n_params(student_module.alphabet_set, n_params=1)

    countries = student_module.get_countries()
    alpha = {chr(i) for i in range(97, 123)}
    provided = set("".join([x.lower() for x in student_module.alphabet_set(countries)]))
    assert provided.issuperset(
        alpha
    ), f"Your set of countries does not provide these letters: {alpha - provided}"
```

Suggestions to add:

alphabet_set = student_module.set_alphabet_set(countries) 
assert(len(alphabet_set) =< 14, f'The amount of countries returned should be 14 or less, yours was ${len(alphabet_set)}')
Reason: According to the exercise, the length of return value should be a list of 14 countries or less. 

assert(type(alphabet_set) == list, f'We expected a list but you returned a {type(alphabet_set)}')
Reason: Exercise asks for a list to be returned, now wincpy gives an OK if you return a string of all alphabet characters. 

Hope I did the asserts correctly.. 
I would be happy to do a pr for this next week. Just to be clear, I haven't done a pr in a while, but if I'm right the flow is:
1. clone repo
2. create branch
3. change code
4. add, commit, push
5. create pr 

Please let me know if I can and if the code I suggested seems ok.

**Comment by Chrisztiaan** [comment]
Fixed in 1.1.3
