### ISSUE TITLE
Wincpy returns wrong message for unique koala check if break is misplaced

### ISSUE THREAD

**Issue by Jelmerro** [WincAcademy/wincpy#32]
The unique koala check function incorrectly accuses some functions that they return duplicates, if the function returns the wrong number of entries for any range. One scenario is shown below, where the break of the loop is misplaced. The following code reproduces this error reliably, even though it does not return duplicates. It does incorrectly return all 29 unique entries if the x argument is 0, but otherwise the function works as expected, without ever returning duplicates. The wincpy error is that the function returns duplicates, which is not accurate.

```python
def unique_koala_facts(x):
    i = 0
    unique_facts = []
    while i < 1000:
        all_facts = random_koala_fact()
        i += 1
        if all_facts not in unique_facts:
            unique_facts.append(all_facts)
            if len(unique_facts) == x:
                break
    return unique_facts
```

**Comment by Chrisztiaan** [comment]
Fixed in 1.1.3
Added a separate check for when argument is 0 to give the student more insight.
