### ISSUE TITLE
Wincpy check for exercise Calculate reliant on only providing a single print statement

### ISSUE THREAD

**Issue by svandriessel** [WincAcademy/wincpy#35]
Lot's of students use extra print statements, so a common error students run into is: 
Output was not as expected:  ValueError: could not convert string to float: '{something they printed}\n73.5'

Suggested solution:
Compare last output line (split on " \n") or check for inclusion in the output.

**Comment by Chrisztiaan** [comment]
Fixed in 1.1.3
