### ISSUE TITLE
Use private package repository 

### ISSUE THREAD

**Issue by sterrenburg** [WincAcademy/wincpy#7]
Use https://packages.wincacademy.nl to distribute package versions. This allows for easier installation by students and prevents students from seeing the source of the package (it is now publicly available).

- [x] Manually add an empty `wincpy` directory to the spaces server.
- [x] Use [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/) to automate release versions.
- [x] Add a workflow for deployment, see [CLI](https://github.com/WincAcademy/cli/blob/main/.github/workflows/ci.yaml) for inspiration.
- [x] Update the README to reflect the new install process + workflow.
- [ ] Inform students + update relevant docs on how to install.
- [ ] Make the wincpy project private.

**Comment by sterrenburg** [comment]
Organization wide secrets for DigitalOcean Spaces are now available

**Comment by sterrenburg** [comment]
It works! To publish a build to packages.wincacademy.nl, you can now smash the button:
![image](https://user-images.githubusercontent.com/13381444/143251267-5461852c-eb44-4d96-98ad-26cf1235a7cb.png)

**Comment by stfwn** [comment]
Great, thanks!!
