### ISSUE TITLE
New check module system

### ISSUE THREAD

**Issue by stfwn** [WincAcademy/wincpy#8]
I recently added a new check module system. Writing a check module with a `run` method is now deprecated. The new format is to write pytest-like check modules:
- Separate requirements into functions with names that start with `check_` (much like pytest's: `test_`) and take the student module as an argument.
- Add a docstring for the function that describes the requirement.
- Use `assert` statements to test the student module with descriptive fail messages. You may use Markdown in the messages.

For example:

```python
def check_foo(student_module):
    """Foo returns a correct bar."""
    assert type(student_module.foo(42)) is str, "`foo(42)` does not return a `str`"
    assert student_module.foo(42) == "bar", "`foo(42)` does not return `'bar'`"
```

## Why is this better?

- The deprecated check module system raises if a student did not implement all expected attributes yet. The new check system reports what's happened and proceeds with the other `check_` functions.
- The new check system uses assertions, which are semantically more in line with what we're actually doing.

For an example, see [the check for calculate](https://github.com/WincAcademy/wincpy/blob/master/wincpy/checks/499e67d5cb54448e93cee7465be2c866.py).

## Can we have fixtures, like Pytest?

If you write a PR that adds it you can have it :dancers: 

---

This issue can be closed if all checks have been ported over to the new system and support for the legacy system has been removed.

**Comment by nielsbom** [comment]
Am I correct in assuming we can start converting the checks?

**Comment by nielsbom** [comment]
Created tasks in Clickup for this: https://app.clickup.com/4666611/v/l/4ed7k-5181
